import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import localFont from 'next/font/local';
import './styles/globals.scss';
import StyledComponentsRegistry from './lib/registry';

const inter = Inter({ subsets: ['latin'] });

const drukFont = localFont({
  src: './fonts/FontsFree-Net-Druk-Wide-Medium.ttf',
});

export const metadata: Metadata = {
  title: 'Berserker Program',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={drukFont.className}>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
