import type { Metadata } from 'next';

import './styles/globals.scss';
import StyledComponentsRegistry from '@/lib/registry';
import { drukFont } from './fonts/fonts';

export const metadata: Metadata = {
  title: 'Berserker Program',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={drukFont.className}>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
